In [30]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

In [31]:
# data = 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-03-churn-prediction/WA_Fn-UseC_-Telco-Customer-Churn.csv'

# !wget $data -O ./03-classification/data-week-3.csv

In [32]:
df = pd.read_csv('./03-classification/data-week-3.csv')

In [33]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [34]:
df.head().T

,0,1,2,3,4
customerID,7590-VHVEG,5575-GNVDE,3668-QPYBK,7795-CFOCW,9237-HQITU
gender,Female,Male,Male,Male,Female
SeniorCitizen,0,0,0,0,0
Partner,Yes,No,No,No,No
Dependents,No,No,No,No,No
tenure,1,34,2,45,2
PhoneService,No,Yes,Yes,No,Yes
MultipleLines,No phone service,No,No,No phone service,No
InternetService,DSL,DSL,DSL,DSL,Fiber optic
OnlineSecurity,No,Yes,Yes,Yes,No
OnlineBackup,Yes,No,Yes,No,No
DeviceProtection,No,Yes,No,Yes,No
TechSupport,No,No,No,Yes,No
StreamingTV,No,No,No,No,No
StreamingMovies,No,No,No,No,No
Contract,Month-to-month,One year,Month-to-month,One year,Month-to-month
PaperlessBilling,Yes,No,Yes,No,Yes
PaymentMethod,Electronic check,Mailed check,Mailed check,Bank transfer (automatic),Electronic check
MonthlyCharges,29.85,56.95,53.85,42.3,70.7
TotalCharges,29.85,1889.5,108.15,1840.75,151.65
Churn,No,No,Yes,No,Yes

In [35]:
df.columns = df.columns.str.lower().str.replace(' ', '_')

In [36]:
categorical_columns = list(df.dtypes[df.dtypes == 'str'].index)

for col in categorical_columns:
    df[col] = df[col].str.lower().str.replace(' ', '_')

In [37]:
df.head().T

,0,1,2,3,4
customerid,7590-vhveg,5575-gnvde,3668-qpybk,7795-cfocw,9237-hqitu
gender,female,male,male,male,female
seniorcitizen,0,0,0,0,0
partner,yes,no,no,no,no
dependents,no,no,no,no,no
tenure,1,34,2,45,2
phoneservice,no,yes,yes,no,yes
multiplelines,no_phone_service,no,no,no_phone_service,no
internetservice,dsl,dsl,dsl,dsl,fiber_optic
onlinesecurity,no,yes,yes,yes,no
onlinebackup,yes,no,yes,no,no
deviceprotection,no,yes,no,yes,no
techsupport,no,no,no,yes,no
streamingtv,no,no,no,no,no
streamingmovies,no,no,no,no,no
contract,month-to-month,one_year,month-to-month,one_year,month-to-month
paperlessbilling,yes,no,yes,no,yes
paymentmethod,electronic_check,mailed_check,mailed_check,bank_transfer_(automatic),electronic_check
monthlycharges,29.85,56.95,53.85,42.3,70.7
totalcharges,29.85,1889.5,108.15,1840.75,151.65
churn,no,no,yes,no,yes

In [38]:
df.dtypes

customerid              str
gender                  str
seniorcitizen         int64
partner                 str
dependents              str
tenure                int64
phoneservice            str
multiplelines           str
internetservice         str
onlinesecurity          str
onlinebackup            str
deviceprotection        str
techsupport             str
streamingtv             str
streamingmovies         str
contract                str
paperlessbilling        str
paymentmethod           str
monthlycharges      float64
totalcharges            str
churn                   str
dtype: object

In [39]:
df.seniorcitizen.unique() # categorical

array([0, 1])

In [40]:
df.totalcharges.unique()[:5] # numerical

<StringArray>
['29.85', '1889.5', '108.15', '1840.75', '151.65']
Length: 5, dtype: str

In [41]:
# pd.to_numeric(df.totalcharges)

```console
ValueError: Unable to parse string "_" at position 488

In [ ]:
tc = pd.to_numeric(df.totalcharges, errors='coerce')

In [45]:
tc.isnull().sum()

np.int64(11)

In [ ]:
df[tc.isnull()][['customerid', 'tenure', 'totalcharges']]

      customerid  tenure totalcharges
488   4472-lvygi       0            _
753   3115-czmzd       0            _
936   5709-lvoeq       0            _
1082  4367-nuyao       0            _
1340  1371-dwpaz       0            _
3331  7644-omvmy       0            _
3826  3213-vvolg       0            _
4380  2520-sgtta       0            _
5218  2923-arzlg       0            _
6670  4075-wkniu       0            _
6754  2775-sefee       0            _

In [53]:
df.totalcharges = pd.to_numeric(df.totalcharges, errors='coerce')
df.totalcharges = df.totalcharges.fillna(0)

In [54]:
df.isnull().sum()

customerid          0
gender              0
seniorcitizen       0
partner             0
dependents          0
tenure              0
phoneservice        0
multiplelines       0
internetservice     0
onlinesecurity      0
onlinebackup        0
deviceprotection    0
techsupport         0
streamingtv         0
streamingmovies     0
contract            0
paperlessbilling    0
paymentmethod       0
monthlycharges      0
totalcharges        0
churn               0
dtype: int64

In [55]:
df.churn.head()

0     no
1     no
2    yes
3     no
4    yes
Name: churn, dtype: str

In [59]:
df.churn = (df.churn.values == 'yes').astype('int')

In [61]:
df.head(3).T

                                 0             1               2
customerid              7590-vhveg    5575-gnvde      3668-qpybk
gender                      female          male            male
seniorcitizen                    0             0               0
partner                        yes            no              no
dependents                      no            no              no
tenure                           1            34               2
phoneservice                    no           yes             yes
multiplelines     no_phone_service            no              no
internetservice                dsl           dsl             dsl
onlinesecurity                  no           yes             yes
onlinebackup                   yes            no             yes
deviceprotection                no           yes              no
techsupport                     no            no              no
streamingtv                     no            no              no
streamingmovies                 no            no              no
contract            month-to-month      one_year  month-to-month
paperlessbilling               yes            no             yes
paymentmethod     electronic_check  mailed_check    mailed_check
monthlycharges               29.85         56.95           53.85
totalcharges                 29.85        1889.5          108.15
churn                            0             0               1

In [62]:
from sklearn.model_selection import train_test_split

In [63]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=1)

$
\boxed{r = \frac{p}{1-q}}
$

Where:

- $p$: Desired proportion of the total dataset.
- $q$: Proportion excluded in the first split.
- $r$: Proportion to split from the remaining data.

$
\rightarrow\frac{20\%}{80\%} = 25\%
$

In [ ]:
train_test_split(df_full_train, test_size=0.25, random_state=1)