In [97]:
import numpy as np
import pandas as pd

In [98]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [99]:
pd.DataFrame(data)

         0         1     2      3  4          5            6      7
0   Nissan    Stanza  1991  138.0  4     MANUAL        sedan   2000
1  Hyundai    Sonata  2017    NaN  4  AUTOMATIC        Sedan  27150
2    Lotus     Elise  2010  218.0  4     MANUAL  convertible  54990
3      GMC    Acadia  2017  194.0  4  AUTOMATIC      4dr SUV  34450
4   Nissan  Frontier  2017  261.0  6     MANUAL       Pickup  32340

In [100]:
df = pd.DataFrame(data, columns=columns)
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [101]:
data = [
    {
        "Make": "Nissan",
        "Model": "Stanza",
        "Year": 1991,
        "Engine HP": 138.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "sedan",
        "MSRP": 2000
    },
    {
        "Make": "Hyundai",
        "Model": "Sonata",
        "Year": 2017,
        "Engine HP": None,
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "Sedan",
        "MSRP": 27150
    },
    {
        "Make": "Lotus",
        "Model": "Elise",
        "Year": 2010,
        "Engine HP": 218.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "convertible",
        "MSRP": 54990
    },
    {
        "Make": "GMC",
        "Model": "Acadia",
        "Year": 2017,
        "Engine HP": 194.0,
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "4dr SUV",
        "MSRP": 34450
    },
    {
        "Make": "Nissan",
        "Model": "Frontier",
        "Year": 2017,
        "Engine HP": 261.0,
        "Engine Cylinders": 6,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "Pickup",
        "MSRP": 32340
    }
]

In [102]:
df = pd.DataFrame(data)
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [103]:
df.head(n=2)

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150

In [104]:
df.Make

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: str

In [105]:
df["Make"]

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: str

In [106]:
df["Engine HP"]

0    138.0
1      NaN
2    218.0
3    194.0
4    261.0
Name: Engine HP, dtype: float64

In [107]:
df[["Make", "Model", "MSRP"]]

      Make     Model   MSRP
0   Nissan    Stanza   2000
1  Hyundai    Sonata  27150
2    Lotus     Elise  54990
3      GMC    Acadia  34450
4   Nissan  Frontier  32340

In [108]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [109]:
df['id'] = ['nis1', 'hyu1', 'lot2', 'gmc1', 'nis2']
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,nis1
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,hyu1
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,lot2
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,gmc1
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,nis2

In [110]:
del df['id']
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [111]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [112]:
df.columns

Index(['Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
       'Transmission Type', 'Vehicle_Style', 'MSRP'],
      dtype='str')

In [113]:
df['Make'].index

RangeIndex(start=0, stop=5, step=1)

In [114]:
df.loc[1]

Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle_Style            Sedan
MSRP                     27150
Name: 1, dtype: object

In [115]:
df.loc[[2, 3]]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450

In [116]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [117]:
df.index = ['a', 'b', 'c', 'd', 'e']
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
a,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
d,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
e,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [118]:
df.loc[['c', 'd']]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
d,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450

In [119]:
df.iloc[[2, 3]]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
d,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450

In [120]:
df.iloc[1]

Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle_Style            Sedan
MSRP                     27150
Name: b, dtype: object

In [121]:
df.reset_index()

,index,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,a,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,d,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,e,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [122]:
df.reset_index(drop=True)

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [123]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
a,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
d,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
e,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [124]:
df = df.reset_index(drop=True)
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [125]:
df["Engine HP"]

0    138.0
1      NaN
2    218.0
3    194.0
4    261.0
Name: Engine HP, dtype: float64

In [126]:
df["Engine HP"] * 2

0    276.0
1      NaN
2    436.0
3    388.0
4    522.0
Name: Engine HP, dtype: float64

In [127]:
df["Year"]

0    1991
1    2017
2    2010
3    2017
4    2017
Name: Year, dtype: int64

In [128]:
df["Year"] >= 2015

0    False
1     True
2    False
3     True
4     True
Name: Year, dtype: bool

In [129]:
df[
    df["Year"] >= 2015
    ]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [130]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [131]:
df[
    (df["Make"] == 'Nissan') & (df["Year"] >= 2015)
]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [132]:
df["Vehicle_Style"]

0          sedan
1          Sedan
2    convertible
3        4dr SUV
4         Pickup
Name: Vehicle_Style, dtype: str

In [133]:
'Hello'.lower()

'hello'

In [134]:
df["Vehicle_Style"].str.lower()

0          sedan
1          sedan
2    convertible
3        4dr suv
4         pickup
Name: Vehicle_Style, dtype: str

In [135]:
'Hello World'.replace(' ', '_')

'Hello_World'

In [136]:
df["Vehicle_Style"] = df["Vehicle_Style"].str.replace(' ', '_').str.lower()

In [137]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr_suv,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,pickup,32340

In [138]:
df.MSRP.max()

np.int64(54990)

In [139]:
df.MSRP.min()

np.int64(2000)

In [140]:
df.MSRP.mean()

np.float64(30186.0)

In [141]:
df.MSRP.describe()

count        5.000000
mean     30186.000000
std      18985.044904
min       2000.000000
25%      27150.000000
50%      32340.000000
75%      34450.000000
max      54990.000000
Name: MSRP, dtype: float64

In [142]:
df.describe().round(2)

          Year  Engine HP  Engine Cylinders      MSRP
count     5.00       4.00              5.00      5.00
mean   2010.40     202.75              4.40  30186.00
std      11.26      51.30              0.89  18985.04
min    1991.00     138.00              4.00   2000.00
25%    2010.00     180.00              4.00  27150.00
50%    2017.00     206.00              4.00  32340.00
75%    2017.00     228.75              4.00  34450.00
max    2017.00     261.00              6.00  54990.00

In [143]:
df.Make.unique()

<StringArray>
['Nissan', 'Hyundai', 'Lotus', 'GMC']
Length: 4, dtype: str

In [144]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr_suv,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,pickup,32340

In [145]:
df.nunique()

Make                 4
Model                5
Year                 3
Engine HP            4
Engine Cylinders     2
Transmission Type    2
Vehicle_Style        4
MSRP                 5
dtype: int64

In [146]:
df.isnull()

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,False,False,False,False,False,False,False,False
1,False,False,False,True,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False

In [147]:
df.isnull().sum()

Make                 0
Model                0
Year                 0
Engine HP            1
Engine Cylinders     0
Transmission Type    0
Vehicle_Style        0
MSRP                 0
dtype: int64

In [148]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr_suv,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,pickup,32340

```
SELECT
    transmission_type,
    AVG(MSRP)
FROM 
    cars
GROUP BY
    transmission_type
```

In [149]:
df.groupby('Transmission Type').MSRP.describe()

,count,mean,std,min,25%,50%,75%,max
Transmission Type,,,,,,,,
AUTOMATIC,2.0,30800.000000,5161.879503,27150.0,28975.0,30800.0,32625.0,34450.0
MANUAL,3.0,29776.666667,26587.836191,2000.0,17170.0,32340.0,43665.0,54990.0

In [150]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr_suv,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,pickup,32340

In [151]:
df.MSRP.values

array([ 2000, 27150, 54990, 34450, 32340])

In [152]:
df.to_dict(orient='records')

[{'Make': 'Nissan',
  'Model': 'Stanza',
  'Year': 1991,
  'Engine HP': 138.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'sedan',
  'MSRP': 2000},
 {'Make': 'Hyundai',
  'Model': 'Sonata',
  'Year': 2017,
  'Engine HP': nan,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': 'sedan',
  'MSRP': 27150},
 {'Make': 'Lotus',
  'Model': 'Elise',
  'Year': 2010,
  'Engine HP': 218.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'convertible',
  'MSRP': 54990},
 {'Make': 'GMC',
  'Model': 'Acadia',
  'Year': 2017,
  'Engine HP': 194.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': '4dr_suv',
  'MSRP': 34450},
 {'Make': 'Nissan',
  'Model': 'Frontier',
  'Year': 2017,
  'Engine HP': 261.0,
  'Engine Cylinders': 6,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'pickup',
  'MSRP': 32340}]

In [153]:
idx = np.arange(5)
idx

array([0, 1, 2, 3, 4])

In [154]:
np.random.seed(4)
np.random.shuffle(idx)
idx

array([0, 3, 1, 4, 2])

In [155]:
df.iloc[idx]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr_suv,34450
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,sedan,27150
4,Nissan,Frontier,2017,261.0,6,MANUAL,pickup,32340
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990

In [156]:
df = df.iloc[idx]

In [157]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr_suv,34450
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,sedan,27150
4,Nissan,Frontier,2017,261.0,6,MANUAL,pickup,32340
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990

In [158]:
df.iloc[[0, 1, 2]]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr_suv,34450
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,sedan,27150

In [159]:
df.loc[[0, 1, 2]]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990

In [160]:
df.index

Index([0, 3, 1, 4, 2], dtype='int64')

In [161]:
df.loc[[0, 1]]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,sedan,27150

In [162]:
df.iloc[[0, 1]]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr_suv,34450

In [163]:
df.reset_index(drop=True)

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr_suv,34450
2,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,sedan,27150
3,Nissan,Frontier,2017,261.0,6,MANUAL,pickup,32340
4,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990

In [164]:
n_train = 3
n_val = 1
n_test = 1

In [165]:
df_train = df.iloc[:n_train]
df_val = df.iloc[n_train:n_train+n_val]
df_test = df.iloc[n_train+n_val:]

In [166]:
df[['Make','Model', 'Year']]

      Make     Model  Year
0   Nissan    Stanza  1991
3      GMC    Acadia  2017
1  Hyundai    Sonata  2017
4   Nissan  Frontier  2017
2    Lotus     Elise  2010

In [167]:
df_train[['Make', 'Model', 'Year']]

      Make   Model  Year
0   Nissan  Stanza  1991
3      GMC  Acadia  2017
1  Hyundai  Sonata  2017

In [168]:
df_val[['Make', 'Model', 'Year']]

     Make     Model  Year
4  Nissan  Frontier  2017

In [169]:
df_test[['Make', 'Model', 'Year']]

    Make  Model  Year
2  Lotus  Elise  2010

In [172]:
df = df.reset_index(drop=True)

In [173]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr_suv,34450
2,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,sedan,27150
3,Nissan,Frontier,2017,261.0,6,MANUAL,pickup,32340
4,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990

In [174]:
df.dtypes

Make                     str
Model                    str
Year                   int64
Engine HP            float64
Engine Cylinders       int64
Transmission Type        str
Vehicle_Style            str
MSRP                   int64
dtype: object

In [175]:
df.dtypes.index

Index(['Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
       'Transmission Type', 'Vehicle_Style', 'MSRP'],
      dtype='str')

In [176]:
df.dtypes == 'str'

Make                  True
Model                 True
Year                 False
Engine HP            False
Engine Cylinders     False
Transmission Type     True
Vehicle_Style         True
MSRP                 False
dtype: bool

In [177]:
df.dtypes[df.dtypes == 'str']

Make                 str
Model                str
Transmission Type    str
Vehicle_Style        str
dtype: object

In [179]:
list(df.dtypes[df.dtypes == 'str'].index)

['Make', 'Model', 'Transmission Type', 'Vehicle_Style']

In [180]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr_suv,34450
2,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,sedan,27150
3,Nissan,Frontier,2017,261.0,6,MANUAL,pickup,32340
4,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990

In [181]:
string_columns = df.dtypes[df.dtypes == 'str'].index
for col in string_columns:
    df[col] = df[col].str.lower().str.replace(' ', '_')
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,nissan,stanza,1991,138.0,4,manual,sedan,2000
1,gmc,acadia,2017,194.0,4,automatic,4dr_suv,34450
2,hyundai,sonata,2017,NaN,4,automatic,sedan,27150
3,nissan,frontier,2017,261.0,6,manual,pickup,32340
4,lotus,elise,2010,218.0,4,manual,convertible,54990

In [186]:
df.Make.values

<StringArray>
['nissan', 'gmc', 'hyundai', 'nissan', 'lotus']
Length: 5, dtype: str

In [187]:
df.Make.value_counts()

Make
nissan     2
gmc        1
hyundai    1
lotus      1
Name: count, dtype: int64

In [188]:
df['Engine HP'].isnull()

0    False
1    False
2     True
3    False
4    False
Name: Engine HP, dtype: bool

In [191]:
df['Engine HP'].fillna(0)

0    138.0
1    194.0
2      0.0
3    261.0
4    218.0
Name: Engine HP, dtype: float64

In [192]:
df['Engine HP'].fillna(df['Engine HP'].mean())

0    138.00
1    194.00
2    202.75
3    261.00
4    218.00
Name: Engine HP, dtype: float64

In [193]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,nissan,stanza,1991,138.0,4,manual,sedan,2000
1,gmc,acadia,2017,194.0,4,automatic,4dr_suv,34450
2,hyundai,sonata,2017,NaN,4,automatic,sedan,27150
3,nissan,frontier,2017,261.0,6,manual,pickup,32340
4,lotus,elise,2010,218.0,4,manual,convertible,54990

In [194]:
df['Engine HP'] = df['Engine HP'].fillna(df['Engine HP'].mean())

In [195]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,nissan,stanza,1991,138.00,4,manual,sedan,2000
1,gmc,acadia,2017,194.00,4,automatic,4dr_suv,34450
2,hyundai,sonata,2017,202.75,4,automatic,sedan,27150
3,nissan,frontier,2017,261.00,6,manual,pickup,32340
4,lotus,elise,2010,218.00,4,manual,convertible,54990

In [197]:
df.sort_values(by='MSRP')

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,nissan,stanza,1991,138.00,4,manual,sedan,2000
2,hyundai,sonata,2017,202.75,4,automatic,sedan,27150
3,nissan,frontier,2017,261.00,6,manual,pickup,32340
1,gmc,acadia,2017,194.00,4,automatic,4dr_suv,34450
4,lotus,elise,2010,218.00,4,manual,convertible,54990

In [198]:
df.sort_values(by="MSRP", ascending=False)

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
4,lotus,elise,2010,218.00,4,manual,convertible,54990
1,gmc,acadia,2017,194.00,4,automatic,4dr_suv,34450
3,nissan,frontier,2017,261.00,6,manual,pickup,32340
2,hyundai,sonata,2017,202.75,4,automatic,sedan,27150
0,nissan,stanza,1991,138.00,4,manual,sedan,2000

```
SELECT 
    transmission_type,
    AVG(MSRP),
    COUNT(MSRP)
FROM 
    cars
GROUP BY
    transmission_type
```

In [208]:
df_group = df.groupby('Transmission Type').MSRP.agg(['mean', 'count'])
df_group

                           mean  count
Transmission Type
automatic          30800.000000      2
manual             29776.666667      3

In [209]:
df_group['mean']

Transmission Type
automatic    30800.000000
manual       29776.666667
Name: mean, dtype: float64

In [210]:
df.MSRP.mean()

np.float64(30186.0)

In [212]:
df_group['mean'] - df.MSRP.mean()

Transmission Type
automatic    614.000000
manual      -409.333333
Name: mean, dtype: float64

In [213]:
df.MSRP

0     2000
1    34450
2    27150
3    32340
4    54990
Name: MSRP, dtype: int64

In [214]:
np.log1p(df.MSRP)

0     7.601402
1    10.447293
2    10.209169
3    10.384091
4    10.914925
Name: MSRP, dtype: float64

In [215]:
np.log1p(df.MSRP.values)

array([ 7.60140233, 10.4472933 , 10.20916916, 10.38409105, 10.91492481])